/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comp370;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author jgman
 */
public class AddProvider extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddProvider
     */
    JFrame intframe=new JFrame();
    public AddProvider() {
        initComponents();
        setVisible(true);
        intframe.add(this);
        intframe.setVisible(true);
        setVisible(true);
        intframe.setSize(400, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        providernumberlbl = new javax.swing.JLabel();
        addproviderbtn = new javax.swing.JButton();
        providernumbertxt = new javax.swing.JTextField();
        provideraddresslbl = new javax.swing.JLabel();
        provideraddresstxt = new javax.swing.JTextField();
        providercitylbl = new javax.swing.JLabel();
        providercitytxt = new javax.swing.JTextField();
        providerstatelbl = new javax.swing.JLabel();
        providerstatetxt = new javax.swing.JTextField();
        providerpostalcodelbl = new javax.swing.JLabel();
        providerpostalcodetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        providerpasslbl = new javax.swing.JLabel();
        providerpasstxt = new javax.swing.JPasswordField();
        providernamelbl = new javax.swing.JLabel();
        providernametxt = new javax.swing.JTextField();

        providernumberlbl.setText("Provider Number");

        addproviderbtn.setText("Add Provider");
        addproviderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproviderbtnActionPerformed(evt);
            }
        });

        provideraddresslbl.setText("Address");

        providercitylbl.setText("City");

        providerstatelbl.setText("State/Province");

        providerpostalcodelbl.setText("Postal Code");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Enter Provider Details");

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        providerpasslbl.setText("Password");

        providernamelbl.setText("Provider Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(provideraddresslbl)
                            .addComponent(providernumberlbl)
                            .addComponent(providercitylbl)
                            .addComponent(providerstatelbl)
                            .addComponent(providerpostalcodelbl)
                            .addComponent(addproviderbtn)
                            .addComponent(providerpasslbl)
                            .addComponent(providernamelbl))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(provideraddresstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(providernumbertxt)
                            .addComponent(providercitytxt)
                            .addComponent(providerstatetxt)
                            .addComponent(providerpostalcodetxt)
                            .addComponent(cancelbtn)
                            .addComponent(providerpasstxt)
                            .addComponent(providernametxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providernumberlbl)
                    .addComponent(providernumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providernamelbl)
                    .addComponent(providernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerpasslbl)
                    .addComponent(providerpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provideraddresslbl)
                    .addComponent(provideraddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providercitylbl)
                    .addComponent(providercitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerstatelbl)
                    .addComponent(providerstatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerpostalcodelbl)
                    .addComponent(providerpostalcodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbtn)
                    .addComponent(addproviderbtn))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        intframe.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void addproviderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproviderbtnActionPerformed
        int pronum= Integer.parseInt(providernumbertxt.getText());
        String proname= providernametxt.getText(),proadd=provideraddresstxt.getText(),procity=providercitytxt.getText();
        String prostate=providerstatetxt.getText(),prozip=providerpostalcodetxt.getText(),passwd=providerpasstxt.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/comp370","KJ","1996");
            Statement st = con.createStatement();
            //System.out.println("here"+pronum+proname+passwd+proadd+procity+prostate+prozip);
            st.executeUpdate("INSERT INTO `provider` (`provider_num`, `provider_name`, `Password`, `Street`, `City`, `State`, `Zip`) VALUES ("
            +pronum+" ,'"+proname+"', '"+passwd+"', '"+proadd+"', '"+procity+"', '"+prostate+"', '"+prozip+"')");
               }
               catch(Exception e){
                   System.out.println("Error");
               }
    }//GEN-LAST:event_addproviderbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addproviderbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel provideraddresslbl;
    private javax.swing.JTextField provideraddresstxt;
    private javax.swing.JLabel providercitylbl;
    private javax.swing.JTextField providercitytxt;
    private javax.swing.JLabel providernamelbl;
    private javax.swing.JTextField providernametxt;
    private javax.swing.JLabel providernumberlbl;
    private javax.swing.JTextField providernumbertxt;
    private javax.swing.JLabel providerpasslbl;
    private javax.swing.JPasswordField providerpasstxt;
    private javax.swing.JLabel providerpostalcodelbl;
    private javax.swing.JTextField providerpostalcodetxt;
    private javax.swing.JLabel providerstatelbl;
    private javax.swing.JTextField providerstatetxt;
    // End of variables declaration//GEN-END:variables
}
